### ISSUE TITLE
https://vcenter6-eqx.noc.lan/rest/vcenter/host/{host} is not available

### ISSUE THREAD

**Issue by bmironer** [vmware/vsphere-automation-sdk-rest#17]
GET /rest/vcenter/host/{host} is currently not implemented. 
So there seems to be no way to obtain host information (such as CPU type).
However the corresponding command exists in the other SDKs in Perl or PowerCLI
and the information exists in vSphere.

**Comment by jrgarcia** [comment]
Getting a single host is currently not implemented through the REST API yet. The information does exist and is available from the SDKs that are backed by the SOAP API. Please do report any inconveniences or issues you run into. It helps us to prioritize. Just out of curiosity, where you exploring with Postman? Were you planning on using one of the SDKs and if so, which one?
