### ISSUE TITLE
How to determine available datastores and networks given a cluster + host?

### ISSUE THREAD

**Issue by NuSkooler** [vmware/vsphere-automation-sdk-rest#19]
Via the REST API I need to determine datastores and networks **available/accessible** to a given cluster + host combination. How is this possible? Hosts is not available as one of the filters for datastores nor networks.

**Comment by alanrenouf** [comment]
Thanks, great feature request, we will add this to our backlog.

**Comment by alanrenouf** [comment]
Just a clarification point, are you expecting to give a host and a cluster and get the datastores and networks available that are common to them both or are you asking to query the cluster for datastores and networks available and query the host for datastores and networks available?

**Comment by NuSkooler** [comment]
@alanrenouf I've since moved to the SOAP implementation, but I will attempt to keep up on these in efforts to better the REST API.

Given a *host*, it would be good to be able to query the available datastores and networks. In SOAP these are properties of the `HostSystem` object for example.

**Comment by alanrenouf** [comment]
Perfect thanks, I appreciate your effort to better the REST API, I hope to make this the BEST place to go in the future and given help from users like you I can make sure we design the API with the latest requirements in mind.

Thanks for the extra info.
