### ISSUE TITLE
Get VM API

### ISSUE THREAD

**Issue by Coada** [vmware/vsphere-automation-sdk-rest#21]
Hello!

I have been scanning the net for information as how to acquire IP information of a created VM, but I am at a loss. Doing a REST request to `{vcenter}/rest/vcenter/vm/{id}` returns every possible information but the one I am looking for. The Vcenter web application however can acquire this information, so it is stored somewhere. How would I go by getting it?

![IPs](https://i.imgur.com/fL6JmZg.png)

**Comment by jrgarcia** [comment]
Hi @Coada! This information is not currently available from the REST API though it is planned. You can use the [management SDK](https://code.vmware.com/web/sdk/65/vsphere-management) or one of the VMOMI (VMware Managed Object Management Interface) SDKs available for several languages here on GitHub ([pyvmomi](https://github.com/vmware/pyvmomi), [govmomi](https://github.com/vmware/govmomi), and [rbvmomi](https://github.com/vmware/rbvmomi)) to get this information right now. Let me know if you have any other questions about the APIs or SDKs.

**Comment by Coada** [comment]
Cool, thanks for the quick reply!
Any VMOMI for Java you might direct me at (that can acquire IPs?)

**Comment by jrgarcia** [comment]
The management SDK that is linked above is written in Java. It isn't available on GitHub (and doesn't have VMOMI in the name), but it pretty much works the same way as the other three. It is actually the original and, I believe, has more features than the others. I'm not sure if it is available via jCenter, Maven, etc. There is documentation available from that same link too.

**Comment by jrgarcia** [comment]
@Coada Also, you could sign up for the beta program. IP addresses will be available in the next version of the REST API (which is in this beta). You can find more information [here](https://blogs.vmware.com/vsphere/2017/10/new-vmware-vsphere-beta-indicate-interest.html).

**Comment by Coada** [comment]
Okay so I've managed to get it working. If anyone else happens to stumble upon this issue too I would redirect you to the example [FindObjects.java](https://github.com/vmwarecode/Get-the-UUID-for-a-Virtual-Machine/blob/master/src/com/vmware/utils/FindObjects.java) as well as the document explaining [Inventory Traversal](https://code.vmware.com/doc/preview?id=4205#/doc/PG_PropertyCollector.7.6.html#1108500).

@jrgarcia Looking forward to the released version of the updated REST API, the Management SDK is horrible to work with!

**Comment by jrgarcia** [comment]
@Coada I won't say it's horrible 😉, but REST is certainly simpler to work with! Glad you got it worked out!

**Comment by kannancorent** [comment]
Hi 
Can i know when will be the REST api for getting IP will be released

**Comment by jrgarcia** [comment]
@kannancorent @Coada This information is now available in 6.7 at `rest/vcenter/vm/{vm}/guest/identity`.

**Comment by alanrenouf** [comment]
AS @jrgarcia stated, this was added in 6.7 and the specifics can be found here: https://vdc-repo.vmware.com/vmwb-repository/dcr-public/423e512d-dda1-496f-9de3-851c28ca0814/0e3f6e0d-8d05-4f0c-887b-3d75d981bae5/VMware-vSphere-Automation-SDK-REST-6.7.0/docs/apidocs/operations/com/vmware/vcenter/vm/guest/identity.get-operation.html

**Comment by Coada** [comment]
Indeed we are running 6.7 now and I can confirm it. I am happy I also can fetch the hostname of the machine :)

Regarding the IP address I still have to get it through the SDK - our network assigns the machines several IPs and it is only on a specific subnet that I can communicate with the machine. This IP is in the "list" of IPs and not the top one. 6.7 does not have support to fetch the list of (all) IPs, correct?

**Comment by thorstenschaefer1976** [comment]
when i query rest/vcenter/vm/{vm}/guest/identity i get only ONE IP.
As shown in Coadas initial post there were multiple IPs. 
It seems actually there is no way to get it with REST or perl API?

**Comment by jrgarcia** [comment]
@thorstenschaefer1976 You are correct. The REST API currently does not have a way to return multiple IPs.

**Comment by thorstenschaefer1976** [comment]
thanks for your fast reply. what else can i do without scraping it from the vcenter UI?

**Comment by jrgarcia** [comment]
There is the [vSphere Perl SDK](https://code.vmware.com/web/sdk/67/vsphere-perl). It uses the SOAP APIs to talk to vSphere which has more information available. I only mention that one specifically since you mentioned Perl. It's also available in Java, C#, Ruby, Python, and Go.

**Comment by nrathaus** [comment]
It seems it has been recently added to vSphere 7.x
https://vmware.github.io/vsphere-automation-sdk-rest/vsphere/operations/com/vmware/vcenter/vm/guest/networking.get-operation.html

**Comment by yk-kawabata** [comment]
vSphere 6.7 can't get all VM's IP addresses for good?

**Comment by nrathaus** [comment]
@yk-kawabata it seems that the API command doesn't provide the IP information, I cannot say if they won't be supporting it as it seems that they don't plan to backport the code to older vSpheres
