### ISSUE TITLE
OpenAPI spec for vSphere automation REST?

### ISSUE THREAD

**Issue by antaln** [vmware/vsphere-automation-sdk-rest#28]
Is there an swagger/openapi specification for the vsphere automation API? It can be used to generate clients for languages without vmware-provided bindings (e.g. Go).

**Comment by jrgarcia** [comment]
Hey, @antaln! We don't have anything published currently, but we may publish something to help with this at some point. Thanks for asking and your interest!

**Comment by mjtrangoni** [comment]
@jrgarcia this would expand the support for **many** other languages! See [here](https://swagger.io/tools/open-source/open-source-integrations/).

**Comment by jrgarcia** [comment]
@mjtrangoni We are actually generating the [Ruby SDK](https://github.com/vmware/vsphere-automation-sdk-ruby) from OpenAPI now. We also have a tool to generate an OpenAPI spec (Swagger ver 2 currently) from our API. You can see that tool [here](https://github.com/vmware/vmware-openapi-generator).
