### ISSUE TITLE
Enable vApp options and configure OVF environment transport for a VM

### ISSUE THREAD

**Issue by kroselle** [vmware/vsphere-automation-sdk-rest#29]
Is it possible to enable vApp options and also choose which transport to use to pass the OVF environment to the guest with the REST APIs?

![image](https://user-images.githubusercontent.com/7606513/43608629-6d009530-9656-11e8-9882-4d13c13e1b3d.png)

My goal is to pass some custom parameters to the VM guest OS so it can configure itself. I was playing around with the idea of putting them in the OVF and then reading them with "vmtoolsd --cmd "info-get guestinfo.ovfenv" on the guest, which we are guaranteed to have. From what I read of the python SDK it is doable but ideally I don't want to introduce that dependency.

**Comment by jrgarcia** [comment]
I'm not sure if that is available from the REST APIs. I'm looking into this and will let you know as soon as I get a definitive answer.

**Comment by kroselle** [comment]
Thanks for the quick update, I have looked for many hours and I agree I don't think it is possible through the REST APIs. I figured it can't hurt to ask the pros as my last resort!

**Comment by jrgarcia** [comment]
@kroselle From someone a bit more knowledgable on the subject:

> Currently it is not possible to dynamically choose the transport via API, [you] would need to set the transport of the VirtualHardwareSection in the OVF descriptor. If [you] have the control on the OVF descriptor, [you] can work around it by setting the transport in the OVF descriptor.
