### ISSUE TITLE
What will I write in the "source" section when I import the clone?

### ISSUE THREAD

**Issue by ahmtxonly** [vmware/vsphere-automation-sdk-rest#45]
![image](https://user-images.githubusercontent.com/36918073/85733458-de90b880-b704-11ea-97da-b05245971a89.png)

**Comment by jrgarcia** [comment]
The `source` should be the MOID (Managed Object ID) of the source VM you want to clone. It should look similar `vm-123` (`vm-` followed by a few numbers). You can find that ID by doing a `GET` on `/rest/vcenter/vm?filter.names=[your VM name]`. It will be the `vm` field in the response.
